name: Update DuckDNS

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update DuckDNS
        run: |
          curl -s "https://www.duckdns.org/update?domains=goestest966.duckdns.org&token=85e1f139-e51e-465b-b171-e53116c0f156&ip="
